name: dbt Cloud - PR Testing

on: 
  pull_request:
    branches: 
      - main

jobs:
  dbt-validate_pr:
    name: dbt PR Validation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Trigger dbt job
      env:
        DBT_API_KEY: ${{ secrets.DBT_API_KEY }}
      run: |
        python ./python/run_and_monitor_dbt_cloud_job.py