name: Sync team dev branches on merge to master

on: 
  push:
    branches: 
      - master
      - 2021-06-11--github_pr_automation_to_team_a

jobs:
  update_team_branches:
    name: Sync team dev branches on merge to master 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        delete-branch: false
        branch: master_to_team_a_sync
        base: team_a
        title: 'Syncing team branch on update to master'
        body: |
          Some description
    
    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
